/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyzer;

import org.junit.Test;
import static org.junit.Assert.*;

import org.hamcrest.CoreMatchers;
import org.junit.Assert;

public class MoodAnalyzerTest {
	@Test
	public void analyzeMood_SadMessage_SAD() throws Exception {
		MoodAnalyzer moodAnalyzer = new MoodAnalyzer();
		String mood = moodAnalyzer.analyzeMood("This is a sad message");
		Assert.assertThat(mood, CoreMatchers.is("SAD"));
	}
}
