/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyzer;

import MoodAnalyzer.MoodAnalysisException.ExceptionType;

public class MoodAnalyzer {
	public String analyzeMood(String message) throws MoodAnalysisException {
		try {
			if(message.length()==0) {
				throw new MoodAnalysisException("Please enter proper message",ExceptionType.ENTERED_EMPTY);
			}
			if (message.contains(("sad"))) {
				return "SAD";
			} else {
				return "HAPPY";
			}
		} catch (NullPointerException e) {
			throw new MoodAnalysisException("Please enter proper message",ExceptionType.ENTERED_NULL);
		}
	}
}
