/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MoodAnalyzer;

public class MoodAnalyzer {
	public String analyzeMood(String message) throws MoodAnalysisException {
		try {
			if (message.contains(("sad"))) {
				return "SAD";
			} else {
				return "HAPPY";
			}
		} catch (NullPointerException e) {
			throw new MoodAnalysisException("Please enter proper message");
		}
	}
}
